[tools]
golang = "1.27"
nodejs = "26.10.0"
pdm = "2.29.2"
python = "3.14"
terraform = "1.16.5"
uv = "0.12.23"
zig = "0.14.0"

[settings]
python_compile = true
experimental = true
idiomatic_version_file_enable_tools = ["python", "node", "terraform"]
quiet = true
