[tools]
elixir = "1.13.3-otp-24"
golang = "1.18"
nodejs = "22.16.0"
pdm = "2.22.0"
python = "3.11"
terraform = "1.1.7"
uv = "0.4.10"
zig = "0.11.0"

[settings]
python_compile = true
experimental = true
idiomatic_version_file_enable_tools = ["python"]
quiet = true
